remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: 
description: I am a results-driven consultant dedicated to guiding enterprises in the seamless integration of data-driven technology solutions. My expertise lies in the areas of business intelligence, data analytics, and data engineering. My current technical toolkit includes Tableau, Alteryx, Snowflake, AWS, dbt, SQL, and Python. I hold a Bachelor of Arts degree in Economics and Chinese, supplemented by a minor in Accounting, from the University of Notre Dame.
logo: assets/img/ChasenBrutocao_photo.jpg
